openapi: 3.0.0
info:
  title: PetSignal API
  description: API for managing pet alerts and notifications
  version: 1.0.0
  
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

security:
  - bearerAuth: []

paths:
  /alerts:
    get:
      summary: List all alerts
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [LOST, FOUND]
        - name: status
          in: query
          schema:
            type: string
            enum: [ACTIVE, RESOLVED]
        - name: countryId
          in: query
          schema:
            type: integer
        - name: cp
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of alerts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alert'
    post:
      summary: Create a new alert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alert'
      responses:
        '201':
          description: Alert created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'

  /alerts/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get an alert by ID
      responses:
        '200':
          description: Alert found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
    put:
      summary: Update an alert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alert'
      responses:
        '200':
          description: Alert updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
    delete:
      summary: Delete an alert
      responses:
        '204':
          description: Alert deleted

  /alerts/{alertId}/photos:
    parameters:
      - name: alertId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: List photos for an alert
      responses:
        '200':
          description: List of photos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Photo'
    post:
      summary: Add a photo to an alert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Photo'
      responses:
        '201':
          description: Photo added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Photo'

  /users:
    get:
      summary: List all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a user by ID
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Update a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete a user
      responses:
        '204':
          description: User deleted

  /subscriptions:
    get:
      summary: List all subscriptions
      parameters:
        - name: userId
          in: query
          schema:
            type: integer
        - name: countryId
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: List of subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
    post:
      summary: Create a new subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '201':
          description: Subscription created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'

  /subscriptions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a subscription by ID
      responses:
        '200':
          description: Subscription found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
    put:
      summary: Update a subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '200':
          description: Subscription updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
    delete:
      summary: Delete a subscription
      responses:
        '204':
          description: Subscription deleted

  /notifications:
    get:
      summary: List all notifications
      parameters:
        - name: userId
          in: query
          schema:
            type: integer
        - name: alertId
          in: query
          schema:
            type: integer
        - name: type
          in: query
          schema:
            type: string
            enum: [EMAIL, SMS]
      responses:
        '200':
          description: List of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
    post:
      summary: Create a new notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '201':
          description: Notification created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'

  /notifications/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a notification by ID
      responses:
        '200':
          description: Notification found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'

  /email-notifications:
    get:
      summary: List all email notifications
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [PENDING, SENT, FAILED]
      responses:
        '200':
          description: List of email notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmailNotification'
    post:
      summary: Create a new email notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailNotification'
      responses:
        '201':
          description: Email notification created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailNotification'

  /sms-notifications:
    get:
      summary: List all SMS notifications
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [PENDING, SENT, FAILED]
      responses:
        '200':
          description: List of SMS notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SmsNotification'
    post:
      summary: Create a new SMS notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsNotification'
      responses:
        '201':
          description: SMS notification created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsNotification'

  /countries:
    get:
      summary: List all countries
      responses:
        '200':
          description: List of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
    post:
      summary: Create a new country
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Country'
      responses:
        '201':
          description: Country created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'

  /countries/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a country by ID
      responses:
        '200':
          description: Country found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
    put:
      summary: Update a country
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Country'
      responses:
        '200':
          description: Country updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
    delete:
      summary: Delete a country
      responses:
        '204':
          description: Country deleted

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    Alert:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        userId:
          type: integer
        type:
          type: string
          enum: [LOST, FOUND]
        status:
          type: string
          enum: [ACTIVE, RESOLVED]
        chipNumber:
          type: string
          description: Chip number of the pet
        sex:
          type: string
          enum: [MALE, FEMALE, UNKNOWN]
        createdAt:
          type: string
          format: date-time
          readOnly: true
        date:
          type: string
          format: date-time
        description:
          type: string
        breed:
          type: string
        cp:
          type: string
          description: Zip code where last seen
        countryId:
          type: integer
      required:
        - userId
        - type
        - status
        - date
        - cp
        - countryId

    Photo:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        alertId:
          type: integer
        url:
          type: string
          format: uri
      required:
        - alertId
        - url

    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 50
        email:
          type: string
          format: email
          maxLength: 100
        subscription_email:
          type: string
          format: email
          maxLength: 100
        phone_number:
          type: string
          maxLength: 20
        role:
          type: string
          enum: [ADMIN, USER]
        createdAt:
          type: string
          format: date-time
          readOnly: true
      required:
        - username
        - email
        - subscription_email
        - role

    Subscription:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        userId:
          type: integer
        cp:
          type: string
        countryId:
          type: integer
        alertType:
          type: string
          enum: [LOST, FOUND]
      required:
        - userId
        - cp
        - countryId
        - alertType

    Notification:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        userId:
          type: integer
        alertId:
          type: integer
        createdAt:
          type: string
          format: date-time
          readOnly: true
        type:
          type: string
          enum: [EMAIL, SMS]
      required:
        - userId
        - alertId
        - type

    EmailNotification:
      type: object
      properties:
        notificationId:
          type: integer
        status:
          type: string
          enum: [PENDING, SENT, FAILED]
        to:
          type: string
          format: email
        subject:
          type: string
        body:
          type: string
      required:
        - notificationId
        - status
        - to
        - subject
        - body

    SmsNotification:
      type: object
      properties:
        notificationId:
          type: integer
        status:
          type: string
          enum: [PENDING, SENT, FAILED]
        phoneNumber:
          type: string
        text:
          type: string
      required:
        - notificationId
        - status
        - phoneNumber
        - text

    Country:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
      required:
        - name 