notifications:
  get:
    operationId: listNotifications
    tags:
      - Notifications
    summary: List all notifications
    parameters:
      - name: userId
        in: query
        schema:
          type: integer
      - name: alertId
        in: query
        schema:
          type: integer
      - name: type
        in: query
        schema:
          type: string
          enum: [EMAIL, SMS]
    responses:
      '200':
        description: List of notifications
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '../components/notifications-components-openapi.yaml#/Notification'
  post:
    operationId: createNotification
    tags:
      - Notifications
    summary: Create a new notification
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../components/notifications-components-openapi.yaml#/Notification'
    responses:
      '201':
        description: Notification created
        content:
          application/json:
            schema:
              $ref: '../components/notifications-components-openapi.yaml#/Notification'
notifications_id:
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
  get:
    operationId: getNotificationById
    tags:
      - Notifications
    summary: Get a notification by ID
    responses:
      '200':
        description: Notification found
        content:
          application/json:
            schema:
              $ref: '../components/notifications-components-openapi.yaml#/Notification'
email-notifications:
  get:
    operationId: listEmailNotifications
    tags:
      - Notifications
    summary: List all email notifications
    parameters:
      - name: status
        in: query
        schema:
          type: string
          enum: [PENDING, SENT, FAILED]
    responses:
      '200':
        description: List of email notifications
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '../components/notifications-components-openapi.yaml#/EmailNotification'
  post:
    operationId: createEmailNotification
    tags:
      - Notifications
    summary: Create a new email notification
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../components/notifications-components-openapi.yaml#/EmailNotification'
    responses:
      '201':
        description: Email notification created
        content:
          application/json:
            schema:
              $ref: '../components/notifications-components-openapi.yaml#/EmailNotification'
sms-notifications:
  get:
    operationId: listSmsNotifications
    tags:
      - Notifications
    summary: List all SMS notifications
    parameters:
      - name: status
        in: query
        schema:
          type: string
          enum: [PENDING, SENT, FAILED]
    responses:
      '200':
        description: List of SMS notifications
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '../components/notifications-components-openapi.yaml#/SmsNotification'
  post:
    operationId: createSmsNotification
    tags:
      - Notifications
    summary: Create a new SMS notification
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../components/notifications-components-openapi.yaml#/SmsNotification'
    responses:
      '201':
        description: SMS notification created
        content:
          application/json:
            schema:
              $ref: '../components/notifications-components-openapi.yaml#/SmsNotification'