subscriptions:
  get:
    operationId: listSubscriptions
    tags:
      - Subscriptions
    summary: List all subscriptions
    parameters:
      - name: userId
        in: query
        schema:
          type: integer
      - name: countryId
        in: query
        schema:
          type: integer
    responses:
      '200':
        description: List of subscriptions
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '../components/subscriptions-components-openapi.yaml#/Subscription'
  post:
    operationId: createSubscription
    tags:
      - Subscriptions
    summary: Create a new subscription
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../components/subscriptions-components-openapi.yaml#/Subscription'
    responses:
      '201':
        description: Subscription created
        content:
          application/json:
            schema:
              $ref: '../components/subscriptions-components-openapi.yaml#/Subscription'
subscriptions_id:
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
  get:
    operationId: getSubscriptionById
    tags:
      - Subscriptions
    summary: Get a subscription by ID
    responses:
      '200':
        description: Subscription found
        content:
          application/json:
            schema:
              $ref: '../components/subscriptions-components-openapi.yaml#/Subscription'
  put:
    operationId: updateSubscription
    tags:
      - Subscriptions
    summary: Update a subscription
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../components/subscriptions-components-openapi.yaml#/Subscription'
    responses:
      '200':
        description: Subscription updated
        content:
          application/json:
            schema:
              $ref: '../components/subscriptions-components-openapi.yaml#/Subscription'
  delete:
    operationId: deleteSubscription
    tags:
      - Subscriptions
    summary: Delete a subscription
    responses:
      '204':
        description: Subscription deleted