openapi: 3.1.0
info:
  title: PetSignal API
  description: API for managing pet alerts and notifications
  version: 1.0.0

tags:
  - name: Alerts
    description: Operations about alerts
  - name: Photos
    description: Operations about alert photos
  - name: Users
    description: Operations about users
  - name: Subscriptions
    description: Operations about subscriptions
  - name: Notifications
    description: Operations about notifications

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

security:
  - bearerAuth: []

paths:
  /alerts:
    $ref: './paths/alert-paths-openapi.yaml#/alerts'
  /alerts/{id}:
    $ref: './paths/alert-paths-openapi.yaml#/alerts_id'
  /alerts/{alertId}/photos:
    $ref: './paths/alert-paths-openapi.yaml#/alerts_id_photos'

  /photos/s3:
    $ref: './paths/s3-photo-paths-openapi.yaml#/photos_s3'

  /users:
    $ref: './paths/users-paths.yaml#/users'
  /users/{id}:
    $ref: './paths/users-paths.yaml#/users_id'

  /subscriptions:
    $ref: './paths/subscriptions-paths-openapi.yaml#/subscriptions'
  /subscriptions/{id}:
    $ref: './paths/subscriptions-paths-openapi.yaml#/subscriptions_id'

  /notifications:
    $ref: './paths/notifications-paths-openapi.yaml#/notifications'
  /notifications/{id}:
    $ref: './paths/notifications-paths-openapi.yaml#/notifications_id'

  /email-notifications:
    $ref: './paths/notifications-paths-openapi.yaml#/email-notifications'

  /sms-notifications:
    $ref: './paths/notifications-paths-openapi.yaml#/sms-notifications'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
