openapi: 3.1.0
info:
  title: PetSignal API
  description: API for managing pet alerts and notifications
  version: 1.0.0

tags:
  - name: Alerts
    description: Operations about alerts
  - name: Photos
    description: Operations about alert photos
  - name: Users
    description: Operations about users
  - name: Subscriptions
    description: Operations about subscriptions
  - name: Notifications
    description: Operations about notifications

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

security:
  - bearerAuth: []

paths:
  /alerts:
    $ref: './openapi/alert-openapi.yaml#/paths/~1alerts'
  /alerts/{id}:
    $ref: './openapi/alert-openapi.yaml#/paths/~1alerts~1{id}'
  /alerts/{alertId}/photos:
    $ref: './openapi/alert-openapi.yaml#/paths/~1alerts~1{id}~1photos'

  /photos/s3:
    $ref: './openapi/s3-photo-openapi.yaml#/paths/~1photos~1s3'

  /users:
    $ref: './openapi/users-openapi.yaml#/paths/~1users'
  /users/{id}:
    $ref: './openapi/users-openapi.yaml#/paths/~1users~1{id}'

  /subscriptions:
    $ref: './openapi/subscriptions-openapi.yaml#/paths/~1subscriptions'
  /subscriptions/{id}:
    $ref: './openapi/subscriptions-openapi.yaml#/paths/~1subscriptions~1{id}'

  /notifications:
    $ref: './openapi/notifications-openapi.yaml#/paths/~1notifications'
  /notifications/{id}:
    $ref: './openapi/notifications-openapi.yaml#/paths/~1notifications~1{id}'

  /email-notifications:
    $ref: './openapi/notifications-openapi.yaml#/paths/~1email-notifications'

  /sms-notifications:
    $ref: './openapi/notifications-openapi.yaml#/paths/~1sms-notifications'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
