Photo:
  type: object
  properties:
    id:
      type: integer
    alertId:
      type: integer
    s3objectKey:
      type: string
  required:
    - alertId
    - url
PhotoUrl:
  type: object
  properties:
    s3ObjectKey:
      type: string
      example: "originalFilename__abc123.jpg"
    presignedUrl:
      type: string
      format: uri
      example: "https:s3.region.aws.com/bucket/originalFilename__abc123.jpg"
  required:
    - s3ObjectKey
    - presignedUrl