Subscription:
  type: object
  properties:
    id:
      type: integer
      readOnly: true
    userId:
      type: integer
    cp:
      type: string
    countryId:
      type: integer
    alertType:
      type: string
      enum: [LOST, FOUND]
  required:
    - userId
    - cp
    - countryId
    - alertType